spring:
  application:
    name: spring-batch-jdbc-paging-reader

  batch:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    batch:
      jdbcUrl: jdbc:postgresql://localhost:5432/spring-batch-jdbc-paging-reader-db
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver

    app:
      jdbcUrl: jdbc:postgresql://localhost:5432/spring-batch-jdbc-paging-reader-app-db
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver

logging:
  level:
    org.hibernate: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.batch.item.database: debug